server:
  port: 9090

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/VTMProjectDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: burhan71
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
